name: Blog API Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    

jobs:
  build:
    steps:
      runs-on: ubuntu-latest
      run: echo "This is my first Github Action"
    


