name: Blog API Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
#Job workflow level concurrency: 
#cancel-in-progress to false means it shouldnt cancel the workflow 
#it will only pause the until the other workflow is finished running
# concurrency: 
#       group: producton-deployment
#       cancel-in-progress: false
# job level environmental variables    
env:
  NAME: JELLO
  PASSWORD: IAMHADES
  
jobs:
  custom_build:
    # if: github.ref == 'refs/heads/main'
    #Job level concurrency
    # concurrency: 
    #   group: producton-deployment
    #   cancel-in-progress: false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    runs-on: ubuntu-latest
    steps:
      - name: Starting Ci/CD Pipeline
        run:  echo "Welcome to my first pipeline"

      - name: Download Code from Repository
        uses: actions/checkout@v4

      - name: Download Node
        uses: actions/setup-node@v4
        with: 
          node-version: 22

      - name: Cahing Dependencies
        uses: actions/cache@v4
        with:
          path: '~/.npm'
          key: "${{runner.os}}-node-modules-${{hashFiles('package-lock.json')}}"
        continue-on-error: true

      #- name: Check package-lock-json hasn't changed
        #id: check-cache
        #run: echo "hash=${{ hashFiles('package-lock.json') }}" >> $GITHUB_OUTPUT
          
      - name: Install Dependencies
        run: npm ci

  test_build:
    needs: custom_build
    runs-on: ubuntu-latest
    steps:
      - name: Checking if the build was successful
        run: |
          echo "The build phase is successful"
          echo ${{vars.NAME}} 

      - name: Logging the github error
        run: ls -
        continue-on-error: true
          
      
      


    


