name: Blog API Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
# job level environmental variables    
env:
  NAME: JELLO
  PASSWORD: IAMHADES
  
jobs:
  custom_build:
    concurrency: 
      group: producton-deployment
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Starting Ci/CD Pipeline
        run:  echo "Welcome to my first pipeline"

      - name: Download Code from Repository
        uses: actions/checkout@v4

      - name: Download Node
        uses: actions/setup-node@v4
        with: 
          node-version: 22

      - name: Install Dependencies
        run: npm ci

  test_build:
    needs: custom_build
    runs-on: ubuntu-latest
    steps:
      - name: Checking if the build was successful
        run: |
          echo "The build phase is successful"
          echo ${{vars.NAME}}  
          echo ${{secrets.PASSWORD}}
          echo ${{toJson(github)}}
      
      


    


